:syntax on
:set background=dark " Highlight searches
:set hls

" Line numbers on the side, and column numbers at the bottom
:set number
:set ruler

" Just stick to 4 spaces instead of tabs
:set smarttab
:set expandtab
:set shiftwidth=4

" http://stackoverflow.com/questions/11560201/backspace-key-not-working-in-vim-vi#11560415
:set backspace=2

" Force myself to use HJKL
noremap <Up> <NOP>
noremap <Down> <NOP>
noremap <Left> <NOP>
noremap <Right> <NOP>
