:syntax on
:set background=dark

" Highlight searches
:set hls

" Line numbers on the side, and column numbers at the bottom
:set number
:set ruler

" Just stick to 4 spaces instead of tabs
:set smarttab
:set expandtab
:set shiftwidth=4

" http://stackoverflow.com/questions/11560201/backspace-key-not-working-in-vim-vi#11560415
:set backspace=2

" Force myself to use HJKL
noremap <Up> <NOP>
noremap <Down> <NOP>
noremap <Left> <NOP>
noremap <Right> <NOP>

call plug#begin('~/.vim/plugged')
Plug 'elixir-lang/vim-elixir'
Plug 'vim-syntastic/syntastic'
Plug 'chase/vim-ansible-yaml'
Plug 'tell-k/vim-autopep8'
call plug#end()

" Syntastic settings
let g:syntastic_enable_signs=0
let g:syntastic_check_on_open = 1
:highlight SyntasticError ctermbg=red ctermfg=black cterm=underline
:highlight SyntasticWarning ctermbg=green ctermfg=black cterm=underline

:autocmd FileType yaml setlocal ts=2 sts=2 sw=2 expandtab

" For macvim
:set guifont=Ubuntu\ Mono:h14

let g:autopep8_max_line_length=120
let g:autopep8_on_save=1
let g:autopep8_disable_show_diff=1
