syntax on
:set background=dark

" Highlight searches
:set hls

" Line numbers on the side, and column numbers at the bottom
:set number
:set ruler

" Just stick to 4 spaces instead of tabs
:set smarttab
:set expandtab
:set shiftwidth=4

" Force myself to use HJKL
noremap <Up> <NOP>
noremap <Down> <NOP>
noremap <Left> <NOP>
noremap <Right> <NOP>

call plug#begin('~/.vim/plugged')
Plug 'elixir-lang/vim-elixir'
Plug 'vim-syntastic/syntastic'
call plug#end()

" Syntastic settings
let g:syntastic_enable_signs=0
let g:syntastic_check_on_open = 1
:highlight SyntasticError ctermbg=red ctermfg=black cterm=underline
:highlight SyntasticWarning ctermbg=green ctermfg=black cterm=underline
